#sensor_msgs/Image of   #<<< OLD REFERENCE FRAME FOR TRACKING
float32[] p0           #<<< OLD LIST OF KLT FEATURES
int16[] oc             #<<< OLD LIST OF FEATURES CENTROIDS
int16[] bx             #<<< OLD LIST OF BOUNDING BOXES
int8[] cl              #<<< OLD LIST OF DETECTED CLASSES
int8 nbx               #<<< NUMBER OF DETECTED OBJECTS 
int8 np0               #<<< NUMBER OF KLT FEATURES IN P0
int16[] npb            #<<< OLD NUMBER OF FEATURES PER BBOX
---
int8 rsp
